Week1
NattyNgrn/safemapp pull request #1
Opened 2023-10-30 16:04 UTC by NattyNgrn

2023-10-30 16:11 UTC, dbritto-dev requested changes

2023-10-30 16:11 UTC, dbritto-dev commented on app/layout.js
> +    </ClerkProvider>
```suggestion
      <html lang="en">
        <body className={`bg-cyan-900 container text-slate-200` }>
          <ClerkProvider>{children}</ClerkProvider>
         </body>
      </html>
```

2023-10-30 16:16 UTC, NattyNgrn commented on app/layout.js
> +    </ClerkProvider>
Fixed it !

2023-10-31 05:08 UTC, zhjiang1103 reviewed
What does authMiddleware do here?

2023-11-22 23:05 UTC, merged